version: "3"

services:
  pihole:
    image: diginc/pi-hole:debian
    container_name: pihole
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:80"
    environment:
      ServerIP: 172.19.0.3
     # WEBPASSWORD: 'insert a web password here or it will be random'
    restart: always
    networks:
      vpn:
        ipv4_address: 172.19.0.3
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - pihole
    networks:
      vpn:
        ipv4_address: 172.19.0.2
    volumes:
      - ovpn-data:/etc/openvpn
volumes:
  ovpn-data:
    external: true
networks:
  vpn:
    external: true
